project:
  type: website
  output-dir: docs
  resources:
    - data/
    - scripts/
  render: 
    - "*.qmd"
    - "!/quizzes"
  
  
website:
  title: "STA323"
  search: false
  navbar:
    background: "#2774AE" # nice blue -- Spring 2023
    left:
      - href: index.qmd
        text: schedule
      - href: syllabus.qmd
        text: syllabus
      - text: projects
        menu:
          - href: mini_project.qmd
            text: mini project
          - href: project.qmd
            text: final project
      - text: links
        menu: 
          - href: https://cmgr.oit.duke.edu/containers
            text: Rstudio containers
          - href: https://edstem.org/us/courses/103562/
            text: Ed discussion
          - href: https://github.com/sta323-fa26
            text: GitHub organization
          - href: git-cheatsheet.qmd
            text: git FAQ
          - href: links.qmd
            text: all links
    
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



